import { useState } from "react";
import { usePrimeTech } from "../contexts/PrimeTechContext";

export function AdminPage() {
  const { company, updateCompany } = usePrimeTech();
  const [form, setForm] = useState(company);
  return <div className="space-y-6"><div><h1 className="pt-page-title">Administração</h1><p className="pt-page-subtitle">Dados da empresa, usuários, perfis e permissões.</p></div><form className="pt-card grid gap-4 md:grid-cols-2" onSubmit={async (e) => { e.preventDefault(); await updateCompany(form); alert("Dados salvos."); }}><div className="md:col-span-2"><h2 className="pt-section-title">Dados da empresa</h2><p className="pt-section-description">Usados automaticamente em orçamentos, OS, garantias e relatórios.</p></div><Field label="Nome fantasia" value={form.trade_name} onChange={(v) => setForm((s) => ({ ...s, trade_name: v }))} /><Field label="Razão social" value={form.legal_name ?? ""} onChange={(v) => setForm((s) => ({ ...s, legal_name: v }))} /><Field label="CNPJ" value={form.document ?? ""} onChange={(v) => setForm((s) => ({ ...s, document: v }))} /><Field label="Inscrição municipal" value={form.municipal_registration ?? ""} onChange={(v) => setForm((s) => ({ ...s, municipal_registration: v }))} /><Field label="Telefone" value={form.phone ?? ""} onChange={(v) => setForm((s) => ({ ...s, phone: v }))} /><Field label="WhatsApp" value={form.whatsapp ?? ""} onChange={(v) => setForm((s) => ({ ...s, whatsapp: v }))} /><Field label="E-mail" value={form.email ?? ""} onChange={(v) => setForm((s) => ({ ...s, email: v }))} /><Field label="Instagram" value={form.instagram ?? ""} onChange={(v) => setForm((s) => ({ ...s, instagram: v }))} /><div className="md:col-span-2"><Field label="Endereço" value={form.address ?? ""} onChange={(v) => setForm((s) => ({ ...s, address: v }))} /></div><div><label className="pt-label">Validade padrão do orçamento (dias)</label><input className="pt-input" type="number" min="1" value={form.budget_validity_days} onChange={(e) => setForm((s) => ({ ...s, budget_validity_days: Number(e.target.value) }))} /></div><div><label className="pt-label">URL da logo</label><input className="pt-input" value={form.logo_url ?? ""} onChange={(e) => setForm((s) => ({ ...s, logo_url: e.target.value }))} /></div><div className="md:col-span-2"><label className="pt-label">Texto de garantia</label><textarea className="pt-input min-h-24" value={form.warranty_text ?? ""} onChange={(e) => setForm((s) => ({ ...s, warranty_text: e.target.value }))} /></div><div className="md:col-span-2 flex justify-end"><button className="pt-btn-primary">Salvar configurações</button></div></form><div className="pt-card"><h2 className="pt-section-title">Usuários e permissões</h2><p className="mt-2 text-sm text-muted">O banco já possui papéis e permissões normalizados. A próxima etapa é criar a tela de convite/criação de usuário via backend seguro.</p></div></div>;
}
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <div><label className="pt-label">{label}</label><input className="pt-input" value={value} onChange={(e) => onChange(e.target.value)} /></div>; }
